meta_product_name: "Cooki"
meta_title: "Cooki - Never forget a birthday"
meta_description: "I'm sur it already happend : 'Oh shit, was-it grandma birthday yesterday ? Oh *****... Ok, i'm calling her right now. With Cooki, it never gonna happend again"
meta_image: "cover.png" # should exist in `app/assets/images/`
